config/routes.rb
Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  root to: 'pages#home'
  devise_for :users, controllers: { invitations: 'admin/invitations' }

  post '/newsletter', to: 'pages#home'
  get '/profile', to: 'dashboards#user_dashboard'

  get 'card_init', to: 'cards#init'
  get 'animal_select', to: 'articles#animal_select'

  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy], path: 'conseils' do
    member do
      post 'submit'
      post 'top'
    end
  end

  resources :cards, only: [:index, :show, :new, :create, :edit, :update], path: 'fiches' do
    member do
      post 'submit'
    end
  end

  resources :brands, only: [:index, :show], path: 'marques'

  namespace :admin do

    get '/profile', to: 'dashboards#admin_dashboard'

    # get '/invite', to: 'invitations#new'
    # post '/invite', to: 'invitations#create'

    resources :articles, only: [:destroy] do
      post '/publish', to: 'articles#publish'
      post '/unpublish', to: 'articles#unpublish'
    end

    resources :cards, only: [:destroy] do
      post '/publish', to: 'cards#publish'
      post '/unpublish', to: 'cards#unpublish'
    end

    resources :brands, only: [:new, :create, :edit, :update, :destroy] do
      resources :products, only: [:create]
    end

    resources :products, only: [:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/brand.rb
class Brand < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many :targets, dependent: :destroy
  has_many :animals, through: :targets
  has_many :products, dependent: :destroy
  has_many :sections, dependent: :destroy

  accepts_nested_attributes_for :sections, reject_if: :all_blank, allow_destroy: true

  has_one_attached :logo
  has_one_attached :banner

  validates :name, presence: true
  validates :description, presence: true
  validates :logo, presence: true
  validates :banner, presence: true

  include PgSearch::Model
  pg_search_scope :brands_search,
    against: [ :name ],
    using: {
      tsearch: { prefix: true }
    }

  def set_targets(params)
    params[:targets].each do |key, value|
      if value == '1' && !self.animals.find_by(name: key)
        Target.create(brand: self, animal: Animal.find_by(name: key))
      elsif value == '0' && self.animals.find_by(name: key)
        self.targets.find_by(animal: Animal.find_by(name: key)).destroy
      end
    end
  end

  def should_generate_new_friendly_id?
    name_changed?
  end
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < ApplicationController
  def new
    authorize :brand, :new?
    @brand = Brand.new
  end

  def create
    authorize :brand, :create?
    @brand = Brand.new(brand_params)

    if @brand.save
      @brand.set_targets(params)
      redirect_to brand_path(@brand)
    else
      render :new
    end
  end

  def edit
    authorize :brand, :edit?
    @brand = Brand.friendly.find(params[:id])
  end

  def update
    authorize :brand, :update?
    @brand = Brand.friendly.find(params[:id])

    if @brand.update(brand_params)
      @brand.set_targets(params)
      redirect_to brand_path(@brand)
    else
      render :edit
    end
  end

  def destroy
    authorize :brand, :destroy?

    @brand = Brand.friendly.find(params[:id])
    @brand.destroy

    respond_to do |format|
      format.html { redirect_to admin_profile_path }
      format.js
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name, :description, :banner, :logo,
      sections_attributes: [:id, :title, :_destroy, paragraphs_attributes: [:id, :title, :body, :thumbnail, :_destroy]])
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_brand, only: [:show]

  def index
    @brands = policy_scope(Brand)

    @pagy, @brands = pagy(
      helpers.brands_search(@brands, params).order(created_at: :desc),
      items: 24,
      link_extra: 'data-remote="true"'
    )
  end

  def show
    authorize @brand
  end

  private

  def set_brand
    @brand = Brand.friendly.find(params[:id])
  end
end

app/helpers/admin/brands_helper.rb
module Admin::BrandsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
  def brands_search(brands, params)
    if params[:filter_data]

      if params[:filter_data][:query].present?
        brands = brands.brands_search(params[:filter_data][:query])
      end

      if params[:animals]
        animals = Animal.where(name: params[:animals].select { |k, v| v == '1' }.keys)

        if !animals.empty?
          brands = brands.select { |b| (b.animals.pluck(:name) & animals.pluck(:name)).any? }
          brands = Brand.where(id: brands.map(&:id)) if !animals.empty?
        end
      end

    end

    return brands
  end
end

app/views/admin/brands/_edit_form.html.erb
<%= simple_form_for brand, url: admin_brand_path, method: :patch do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation" class="mb-5">
      <% brand.errors.full_messages.each_with_index do |msg, index| %>
        <% if index == brand.errors.count - 1 %>
          <span><%= msg %></span>
        <% else %>
          <span><%= msg %> / </span>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="form-wrapper brand-form-wrapper">
    <div class="brand-main-fields fields-area">
      <h2>Modifier la marque: <%= brand.name %></h2>
      <div class="row">
        <div class="col-12">
          <%= f.input :name, placeholder: 'Nom de la marque', label: false %>
        </div>
        <div class="col-12">
          <%= f.input :description, as: :text, placeholder: 'Description courte', label: false %>
        </div>
      </div>
      <hr class="my-5" style="width: 70% !important;">
      <div class="row brand-inputs-1">
        <div class="col-2">
          <div class="file-input">
            <%= f.input :banner, direct_upload: true, label: 'Banniere', required: true %>
            <span class="file-upload-value"></span>
          </div>
        </div>
        <div class="col-2">
          <div class="file-input">
            <%= f.input :logo, direct_upload: true, label: 'Logo' %>
            <span class="file-upload-value"></span>
          </div>
        </div>
        <div class="icons-wrapper icons-wrapper-brand-form col-8">
          <div class="icons-form">
            <div class="animals-icons">
              <h3>Cibles de la marque</h3>
              <div class="animals-icons-container">
                <%= simple_fields_for :targets do |fa| %>
                  <% Animal.all.each do |animal| %>
                    <div class="icon-<%= animal.name %>">
                      <% if brand.animals.where(id: animal.id).count > 0 %>
                        <%= fa.input animal.name.to_sym, as: :boolean, input_html: { checked: true, class: 'd-none check-box' } %>
                      <% else %>
                        <%= fa.input animal.name.to_sym, as: :boolean, input_html: { class: 'd-none check-box' } %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr class="my-5">

    <div id="sections">
      <h2>Onglets</h2>
      <div class="row mx-auto">

        <%= f.simple_fields_for :sections do |section| %>
          <%= render 'section_fields', :f => section %>
        <% end %>

        <div class='links col-12 d-flex justify-content-center align-items-center'>
          <%= link_to_add_association 'Ajouter un onglet', f, :sections, class: 'petch-btn mt-5' %>
        </div>

      </div>
    </div>

    <hr class="my-5" style="width: 70% !important;">

    <div class="col-12 pt-5">
      <div class="d-flex justify-content-center pt-3">
        <button type="submit" class="btn petch-btn" data-disable-with="<i class='fas fa-spinner fa-spin'></i>">Modifier la marque</button>
      </div>
    </div>

  </div>
<% end %>

app/views/admin/brands/_new_form.html.erb
<%= simple_form_for brand, url: admin_brands_path, method: :post do |f| %>
  <% if brand.errors.any? %>
    <div id="error_explanation" class="mb-5">
      <% brand.errors.full_messages.each_with_index do |msg, index| %>
        <% if index == brand.errors.count - 1 %>
          <span><%= msg %></span>
        <% else %>
          <span><%= msg %> / </span>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <div class="form-wrapper brand-form-wrapper">
    <div class="brand-main-fields fields-area">
      <h2>Créer une marque</h2>
      <div class="row">
        <div class="col-12">
          <%= f.input :name, placeholder: 'Nom de la marque', label: false %>
        </div>
        <div class="col-12">
          <%= f.input :description, as: :text, placeholder: 'Description courte', label: false %>
        </div>
      </div>
      <hr class="my-5" style="width: 70% !important;">
      <div class="row brand-inputs-1">
        <div class="col-2">
          <div class="file-input">
            <%= f.input :banner, direct_upload: true, label: 'Banniere', required: true %>
            <span class="file-upload-value"></span>
          </div>
        </div>
        <div class="col-2">
          <div class="file-input">
            <%= f.input :logo, direct_upload: true, label: 'Logo' %>
            <span class="file-upload-value"></span>
          </div>
        </div>
        <div class="icons-wrapper icons-wrapper-brand-form col-8">
          <div class="icons-form">
            <div class="animals-icons">
              <h3>Cibles de la marque</h3>
              <div class="animals-icons-container">
                <%= simple_fields_for :targets do |fa| %>
                  <% Animal.all.each do |animal| %>
                    <div class="icon-<%= animal.name %>">
                      <% if brand.animals.where(id: animal.id).count > 0 %>
                        <%= fa.input animal.name.to_sym, as: :boolean, input_html: { checked: true, class: 'd-none check-box' } %>
                      <% else %>
                        <%= fa.input animal.name.to_sym, as: :boolean, input_html: { class: 'd-none check-box' } %>
                      <% end %>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <hr class="my-5">

    <div id="sections">
      <h2>Onglets</h2>
      <div class="row mx-auto">

        <%= f.simple_fields_for :sections do |section| %>
          <%= render 'section_fields', :f => section %>
        <% end %>

        <div class='links col-12 d-flex justify-content-center align-items-center'>
          <%= link_to_add_association 'Ajouter un onglet', f, :sections, class: 'petch-btn mt-5' %>
        </div>

      </div>
    </div>

    <hr class="my-5" style="width: 70% !important;">

    <div class="col-12 pt-5">
      <div class="d-flex justify-content-center pt-3">
        <button type="submit" class="btn petch-btn" data-disable-with="<i class='fas fa-spinner fa-spin'></i>">Creer la marque</button>
      </div>
    </div>

  </div>
<% end %>

app/views/admin/brands/_paragraph_fields.html.erb
<div class='nested-fields col-4'>
    <div class="file-input">
      <span class="file-upload-value"></span>
      <%= f.input :thumbnail, label: 'Image' %>
    </div>
    <%= f.input :title, label: false, placeholder: 'Titre' %>
    <%= f.input :body, label: false, placeholder: 'Contenu' %>
    <%= link_to_remove_association '<i class="far fa-trash-alt"></i>'.html_safe, f, class: 'destroy-nested-btn' %>
</div>

app/views/admin/brands/_section_fields.html.erb
<div class='nested-fields col-12 fields-area section-fields-area'>
  <div class="section-title">
    <h2><%= f.object.title ? f.object.title : 'Nouvel onglet' %></h2>
    <%= link_to_remove_association '<i class="far fa-trash-alt"></i>'.html_safe, f, class: 'destroy-nested-btn' %>
  </div>
  <%= f.input :title, placeholder: 'Titre de l\'onglet', label: false, hint: 'lettres de A à Z (majuscule ou minuscule) OU un chiffre de 0 à 9' %>

  <hr class="my-5" style="width: 70% !important;">

  <div id='paragraphs'>
    <div class="row mx-auto paragraphs-row" style="max-height: 400px; overflow: hidden;">
      <%= f.simple_fields_for :paragraphs, f.object.paragraphs.sort_by(&:created_at) do |paragraph| %>
        <%= render 'paragraph_fields', :f => paragraph %>
      <% end %>
      <div class='links col-4 new-paragraph-wrapper'>
        <%= link_to_add_association '+', f, :paragraphs, class: 'plus-btn' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/brands/destroy.js.erb
document.querySelector("#brand-<%= @brand.id %>").remove();

app/views/admin/brands/edit.html.erb
<div class="dashboard-header">
  <div class="dashboard-header-content">
    <% if current_user.is_admin? %>
      <h1>Mon Profil Admin</h1>
    <% else %>
      <h1>Mon Profil Editeur</h1>
    <% end %>
  </div>
</div>
<div class="container translate-nav py-5">
  <div class="form-content">
    <%= render "edit_form", brand: @brand %>
  </div>
</div>

app/views/admin/brands/new.html.erb
<div class="dashboard-header">
  <div class="dashboard-header-content">
    <% if current_user.is_admin? %>
      <h1>Mon Profil Admin</h1>
    <% else %>
      <h1>Mon Profil Editeur</h1>
    <% end %>
  </div>
</div>
<div class="container translate-nav py-5">
  <div class="form-content">
    <%= render "new_form", brand: @brand %>
  </div>
</div>