config/routes.rb
Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  root to: 'pages#home'
  devise_for :users, controllers: { invitations: 'admin/invitations' }

  post '/newsletter', to: 'pages#home'
  get '/profile', to: 'dashboards#user_dashboard'

  get 'card_init', to: 'cards#init'
  get 'animal_select', to: 'articles#animal_select'

  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy], path: 'conseils' do
    member do
      post 'submit'
      post 'top'
    end
  end

  resources :cards, only: [:index, :show, :new, :create, :edit, :update], path: 'fiches' do
    member do
      post 'submit'
    end
  end

  resources :brands, only: [:index, :show], path: 'marques'

  namespace :admin do

    get '/profile', to: 'dashboards#admin_dashboard'

    # get '/invite', to: 'invitations#new'
    # post '/invite', to: 'invitations#create'

    resources :articles, only: [:destroy] do
      post '/publish', to: 'articles#publish'
      post '/unpublish', to: 'articles#unpublish'
    end

    resources :cards, only: [:destroy] do
      post '/publish', to: 'cards#publish'
      post '/unpublish', to: 'cards#unpublish'
    end

    resources :brands, only: [:new, :create, :edit, :update, :destroy] do
      resources :products, only: [:create]
    end

    resources :products, only: [:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_articles_list.html.erb
<div class="row mb-5">
  <% articles.each_with_index do |article, index| %>
    <div class="col-xs-12 col-md-4 card-container d-flex justify-content-center">
      <%= link_to article_path(article) do %>
        <div class="article-card">
          <div class="card-thumbnail-container">
            <%= image_tag url_for(article.thumbnail) %>
          </div>
          <div class="card-desc mt-1">
            <h4><%= article.title %></h4>
            <p><%= article.subtitle.truncate(55) %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="pagination">
  <%= render 'shared/pagination', pagy: @pagy %>
</div>

app/views/shared/_brands_list.html.erb
<div class="row mb-5">
  <% brands.each_with_index do |brand, index| %>
    <div class="col-12 col-sm-6 col-md-4 card-container d-flex justify-content-center">
      <%= link_to brand_path(brand) do %>
        <div class="article-card brand-card">
          <div class="card-thumbnail-container">
            <%= image_tag url_for(brand.logo) %>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="pagination">
  <%= render 'shared/pagination', pagy: @pagy %>
</div>

app/views/shared/_cards_list.html.erb
<div class="row mb-5">
  <% cards.sort_by { |c| c.specie.name } .each_with_index do |card, index| %>
    <div class="col-12 col-sm-6 col-md-4 card-container d-flex justify-content-center">
      <%= link_to card_path(card) do %>
        <div class="article-card">
          <div class="card-thumbnail-container">
            <%= image_tag url_for(card.thumbnail) %>
          </div>
          <div class="card-desc mt-1">
            <h4><%= card.specie.name %></h4>
            <p><%= raw card.subtitle.truncate(55) %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>
<div class="pagination">
  <%= render 'shared/pagination', pagy: @pagy %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <section class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-3 footer-left">
        <div class="list-social-medias">
          <h4>Suivez-nous !</h4>
          <div class="footer-social-links">
            <span class="icon-fb"><%= link_to('<i class="fab fa-facebook"></i>'.html_safe, "https://www.facebook.com/Petch-105026947504327/") %></span>
            <span class="icon-twitter"><%= link_to('<i class="fab fa-twitter"></i>'.html_safe, "https://twitter.com/Petch_fr") %></span>
            <span class="icon-insta"><%= link_to('<i class="fab fa-instagram"></i>'.html_safe, "https://www.instagram.com/petch_fr/") %></span>
            <span class="icon-youtube"><%= link_to('<i class="fab fa-youtube"></i>'.html_safe, "https://www.youtube.com/channel/UC0r0ZfnEKSTQ7zVFAVvShyg") %></span>
          </div>

          <div class="newsletter">
            <span>NEWSLETTER</span>
            <%= simple_form_for :newsletter, url: newsletter_path, method: :post, remote: true do |f| %>
              <div class="form-group">
                <%= f.input :email, placeholder: 'Email', label: false %>
              </div>
              <%= f.submit 'Je m\'abonne', class: 'btn btn-default' %>
            <% end %>
          </div>
        </div>

      </div>
      <div class="col-xs-12 col-sm-9 list-menus">
        <div class="row menus">
          <div class="col-xs-12 col-sm-4 menus__inside">
            <h4>Aide</h4>
            <span class="collapser-container">
              <button class="btn btn-primary col-xs-12 collapser" type="button" data-target="#collapse-footer-1" aria-expanded="false" aria-controls="collapse-footer-1">
                Aide
              </button>
              <i class="fas fa-chevron-down"></i>
            </span>

            <div class="collapsed-content hidden" id="collapse-footer-1">
              <div class="well">
                <ul class="list-unstyled">
                  <li><a href="https://www.petch.fr/profil">Mon compte</a></li>
                  <li><a href="https://www.petch.fr/profil/commandes">Suivi de commande</a></li>
                  <li><a href="https://www.petch.fr/livraison-retour">Livraison &amp; retour</a></li>
                  <li><a href="https://www.petch.fr/faq-aide">FAQ/Aide</a></li>
                  <li><a href=" https://www.petch.fr/profil/favoris">Wishlist</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div class="col-xs-12 col-sm-4 menus__inside">
            <h4>Catégories</h4>
            <span class="collapser-container">
              <button class="btn btn-primary col-xs-12 collapser" type="button" data-target="#collapse-footer-2" aria-expanded="false" aria-controls="collapse-footer-2">
                Catégories
              </button>
              <i class="fas fa-chevron-down"></i>
            </span>
              <div class="collapsed-content hidden" id="collapse-footer-2">
                <div class="well">
                  <ul class="list-unstyled">
                    <li><a href="https://www.petch.fr/c/chiens?categories=1857">Chiens</a></li>
                    <li><a href="https://www.petch.fr/c/chats?categories=2068">Chats</a></li>
                    <li><a href="https://www.petch.fr/c/rongeurs-2?categories=2238">Rongeurs</a></li>
                    <li><a href="https://www.petch.fr/c/oiseaux-2?categories=2312">Oiseaux</a></li>
                    <li><a href="https://www.petch.fr/">Nos conseils</a></li>
                  </ul>
                </div>
              </div>
            </div>

            <div class="col-xs-12 col-sm-4 menus__inside">
              <h4>A propos</h4>
              <span class="collapser-container">
                <button id="last-btn" class="btn btn-primary col-xs-12 collapser" type="button" data-target="#collapse-footer-3" aria-expanded="false" aria-controls="collapse-footer-3">
                  A propos
                </button>
                <i class="fas fa-chevron-down"></i>
              </span>

              <div class="collapsed-content hidden" id="collapse-footer-3">
                <div class="well">
                  <ul class="list-unstyled">
                    <li><a href="https://www.petch.fr/qui-sommes-nous">Qui sommes-nous ?</a></li>
                    <li><a href="https://petch.fr/on-recrute">On recrute !</a></li>
                    <li><a href="https://www.petch.fr/protection-des-donnees">Protection des données</a></li>
                    <li><a href="https://www.petch.fr/mentions-legales">Mentions légales</a></li>
                    <li><a href="https://www.petch.fr/conditions-generales-d-utilisation">Conditions générales d'utilisation</a></li>
                    <li><%= link_to 'Espace rédacteur', new_user_session_path %></li>
                    <% if user_signed_in? %>
                      <li><%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %></li>
                    <% end %>
                  </ul>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="row second-row">
      <div class="col-xs-12 col-sm-3 list-copyright">
        <p>© Petch 2020</p>
      </div>
      <div class="col-xs-12 col-sm-9 list-payment">
        <div class="block">
          <a href=" https://www.petch.fr/devenir-vendeur">
            <h5>Devenir marchand</h5>
          </a>
          <%= image_tag "visa.png" %>
        </div>
      </div>
    </div>
  </section>
</footer>

app/views/shared/_modal_footer.html.erb
<div class="row" style="width: 108%;">
  <% if brand.products.size > 0 %>
    <h5 class="modal-title" id="exampleModalLabel">Tout les produits</h5>
  <% else %>
    <h5 class="modal-title" id="exampleModalLabel">Pas encore de produits</h5>
  <% end %>
  <% brand.products.each do |product| %>
    <div class="col-12" id="product-col-<%= product.id %>">
      <div class="card-product">
        <%= image_tag url_for(product.thumbnail), alt: "alttext" %>
        <div class="card-product-infos">
          <h2><%= product.name %></h2>
        </div>
        <span class="delete-product">
          <%= link_to admin_product_path(product), method: :delete, remote: true do %>
            <i class="far fa-times-circle"></i>
          <% end %>
        </span>
      </div>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<header class="nav-wrapper">
  <div class="nav-container">
    <span class="nav-logo">
      <%= link_to root_path do %>
        <%= image_tag('logo.png') %>
      <% end %>
    </span>

    <div class="nav-menu-mobile">
      <span class="nav-logo-mobile">
        <%= link_to root_path do %>
          <%= image_tag('icons/brandmark-design.png') %>
        <% end %>
      </span>
      <div class="nav-burger-mobile nav-item dropdown">
        <a class="dropdown-toggle" href="#" id="mobileMenuToggle" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <%= image_tag("icons/menu.png") %>
        </a>
        <div class="dropdown-menu" aria-labelledby="mobileMenuToggle">
          <div class="brand-and-close">
            <%= link_to root_path do %>
              <%= image_tag('icons/brandmark-design.png') %>
            <% end %>
            <div class="close-cross">
              <%= image_tag('icons/close-cross.png') %>
            </div>
          </div>

          <%= link_to 'Fiches', cards_path, class: 'dropdown-item' %>
          <%= link_to 'Conseils', articles_path, class: 'dropdown-item' %>
          <%= link_to 'Marques', brands_path, class: 'dropdown-item' %>
          <a href="https://www.petch.fr" class="dropdown-item shop">Boutique</a>
          <div class="dropdown-divider"></div>
          <%= link_to 'Profil', "https://petch.fr/profil", class: 'dropdown-item' %>
        </div>
      </div>
    </div>



    <div class="nav-menu-desktop">
      <div class="dropdown">
        <button class="dropbtn"><%= link_to 'Fiches', cards_path %></button>
        <div class="dropdown-content">
          <div class="content-content">
            <div class="submenu-categories">
              <%= link_to "Chiens", cards_path(params: {animal: 'chien'}), class: "submenu-activate-button dog-submenu-card" %>
              <%= link_to "Chats", cards_path(params: {animal: 'chat'}), class: "submenu-activate-button cat-submenu-card" %>
              <%= link_to "Rongeurs", cards_path(params: {animal: 'rongeur'}), class: "submenu-activate-button rodent-submenu-card" %>
            </div>
            <div class="submenu-recos-container">
              <div class="submenu-recos-cards submenu-reco-all-card">
                <% Card.where({status: "published"}).last(3).each do |card| %>
                  <%= link_to card_path(card) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(card.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= card.specie.name.truncate(45) %></div>
                      <div class="subtitle"><%= card.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="submenu-recos-cards submenu-reco-dog-card hidden">
                <% Card.where({status: "published", animal: Animal.find_by(name: "chien")}).last(3).each do |card| %>
                  <%= link_to card_path(card) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(card.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= card.specie.name.truncate(45) %></div>
                      <div class="subtitle"><%= card.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="submenu-recos-cards submenu-reco-cat-card hidden">
                <% Card.where({status: "published", animal: Animal.find_by(name: "chat")}).last(3).each do |card| %>
                  <%= link_to card_path(card) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(card.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= card.specie.name.truncate(45) %></div>
                      <div class="subtitle"><%= card.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="submenu-recos-cards submenu-reco-rodent-card hidden">
                <% Card.where({status: "published", animal: Animal.find_by(name: "rongeur")}).last(3).each do |card| %>
                  <%= link_to card_path(card) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(card.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= card.specie.name.truncate(45) %></div>
                      <div class="subtitle"><%= card.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="dropdown">
        <button class="dropbtn"><%= link_to 'Conseils', articles_path %></button>
        <div class="dropdown-content">
          <div class="content-content">
            <div class="submenu-categories">
              <%= link_to "Chiens", articles_path(params: {animal: 'chien'}), class: "submenu-activate-button dog-submenu-article" %>
              <%= link_to "Chats", articles_path(params: {animal: 'chat'}), class: "submenu-activate-button cat-submenu-article" %>
              <%= link_to "Rongeurs", articles_path(params: {animal: 'rongeur'}), class: "submenu-activate-button rodent-submenu-article" %>
            </div>
            <div class="submenu-recos-container">
              <div class="submenu-recos-articles submenu-reco-all-article">
                <% Article.where({status: "published"}).last(3).each do |article| %>
                  <%= link_to article_path(article) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(article.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= article.title.truncate(45) %></div>
                      <div class="subtitle"><%= article.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="submenu-recos-articles submenu-reco-dog-article hidden">
                <% Article.where({status: "published", animal: Animal.find_by(name: "chien")}).last(3).each do |article| %>
                  <%= link_to article_path(article) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(article.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= article.title.truncate(45) %></div>
                      <div class="subtitle"><%= article.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="submenu-recos-articles submenu-reco-cat-article hidden">
                <% Article.where({status: "published", animal: Animal.find_by(name: "chat")}).last(3).each do |article| %>
                  <%= link_to article_path(article) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(article.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= article.title.truncate(45) %></div>
                      <div class="subtitle"><%= article.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
              <div class="submenu-recos-articles submenu-reco-rodent-article hidden">
                <% Article.where({status: "published", animal: Animal.find_by(name: "rongeur")}).last(3).each do |article| %>
                  <%= link_to article_path(article) do %>
                    <div class="submenu-card">
                      <%= image_tag url_for(article.thumbnail), class: 'submenu-picture' %>
                      <div class="name"><%= article.title.truncate(45) %></div>
                      <div class="subtitle"><%= article.subtitle.truncate(50) %></div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>

      <button class="dropbtn"><%= link_to 'Marques', brands_path %></button>
      <div class="shop-container">
        <%= link_to 'https://www.petch.fr', class: 'shop-btn' do %>
          Boutique
        <% end %>
      </div>
    </div>

    <div class="right-box">
      <div class="nav-search">
        <% if params[:controller] == 'articles' && params[:action] == 'index' %>
          <!-- AJAX SEARCH -->
          <%= form_tag articles_path, method: :get, id: 'search-form', remote: true do %>
            <%= text_field_tag :query,
              params[:query],
              placeholder: "Recherche"
            %>
            <%= submit_tag "Search", class: 'd-none' %>
          <% end %>
        <% else %>
          <!-- NON AJAX SEARCH -->
          <%= form_tag articles_path, method: :get, id: 'search-form' do %>
            <%= text_field_tag :query,
              params[:query],
              placeholder: "Recherche"
            %>
            <%= submit_tag "Search", class: 'd-none' %>
          <% end %>
        <% end %>
      </div>

      <div class="nav-menu-mobile">
        <div class="nav-basket-link">
          <%= link_to "https://petch.fr/panier", class: "nav-link-link" do %>
            <%= image_tag url_for("icons/shopping-bag.png") %>
          <% end %>
        </div>
        <div class="nav-heart-link">
          <%= link_to "https://petch.fr/profil/favoris", class: "nav-link-link" do %>
            <%= image_tag url_for("icons/heart.png") %>
          <% end %>
        </div>
      </div>

      <div class="nav-user-menu">
        <div class="nav-basket-link">
          <%= link_to "https://petch.fr/panier", class: "nav-link-link" do %>
            <%= image_tag url_for("icons/shopping-bag.png") %>
          <% end %>
        </div>
        <div class="nav-heart-link">
          <%= link_to "https://petch.fr/profil/favoris", class: "nav-link-link" do %>
            <%= image_tag url_for("icons/heart.png") %>
          <% end %>
        </div>
        <div class="nav-user-link">
           <%= link_to "https://petch.fr/profil", class: "nav-link-link" do %>
                <%= image_tag url_for("icons/avatar.png") %>
              <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/shared/_new_product_modal.html.erb
<!-- Button trigger modal -->
<span data-toggle="modal" data-target="#brand-product-<%= brand.id %>">
  <i class="fas fa-plus-circle"></i>
  <a class="product-modal-btn">Produit</a>
</span>

<!-- Modal -->
<div class="modal fade" id="brand-product-<%= brand.id %>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Nouveau produit "<%= brand.name %>"</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="product-form-wrapper" id="product-brand-<%= brand.id %>-wrapper">
          <%= simple_form_for([brand, Product.new], url: admin_brand_products_path(brand), method: :post, remote: true) do |f| %>
            <div class="form-row">
              <div class="col-8 d-flex align-items-center justify-content-center">
                <%= f.input :name, input_html: { id: "name-#{brand.id}" }, label: false, placeholder: 'Nom du produit' %>
              </div>
              <div class="col-4 d-flex align-items-center justify-content-center">
                <%= f.input :thumbnail, input_html: { id: "thumbnail-#{brand.id}" }, label: 'Image' %>
              </div>
            </div>
            <button type="submit" class="petch-btn modal-btn" data-disable-with="<i class='fas fa-spinner fa-spin'></i>">Creer un produit</button>
          <% end %>
        </div>
      </div>
      <div class="modal-footer" id="modal-footer-<%= brand.id %>">
        <%= render 'shared/modal_footer', brand: brand %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_pagination.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").
  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy) -%>
<%#                            -%><nav aria-label="pager" class="pagy_nav pagination" role="navigation">
<% if pagy.prev                -%>  <span class="page prev"><%== link.call(pagy.prev, '<', 'aria-label="previous"') %></span>
<% else                        -%>  <span class="page prev disabled"><%== '<' %></span>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>  <span class="page"><%== link.call(item) %></span>
<%   elsif item.is_a?(String)  -%>  <span class="page current"><%= item %></span>
<%   elsif item == :gap        -%>  <span class="page gap"><%== pagy_t('pagy.nav.gap') %></span>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>  <span class="page next"><%== link.call(pagy.next, '>', 'aria-label="next"') %></span>
<% else                        -%>  <span class="page next disabled"><%== '>' %></span>
<% end                         -%>
<%#                            -%></nav>

app/views/shared/_registration_edit_form.html.erb
<div class="container d-flex-center mb-5">
  <div class="user-form-wrapper fields-area" style="width: 80%;">
    <%= simple_form_for(current_user, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
      <%= f.error_notification %>

      <div class="d-flex-between">
        <h2>Modifier votre profil ?</h2>
        <%= f.input :avatar, label: "Photo de profil" %>
      </div>
      <div class="form-inputs">
        <div class="row">
          <div class="col-6">
            <%= f.input :first_name,
                        label: 'Prénom',
                        placeholder: 'Votre Prénom',
                        required: false %>
          </div>
          <div class="col-6">
            <%= f.input :last_name,
                        label: 'Nom',
                        placeholder: 'Votre Nom',
                        required: false %>
          </div>
          <div class="col-6">
            <%= f.input :profession,
                        label: 'Profession',
                        placeholder: 'Metier, Activité',
                        hint: 'Vétérinaire, Eleveur canin...',
                        required: false %>
          </div>
          <div class="col-6">
            <%= f.input :signature,
                        label: 'Signature',
                        placeholder: 'Dr. John Doe',
                        hint: 'Cette signature apparaitra en en-tête des conseils',
                        required: false %>
          </div>
          <div class="col-12">
            <h5 class="my-3">Changer de mot de passe ?</h5>
          </div>
          <div class="col-6">
            <%= f.input :password,
                        hint: ("#{@minimum_password_length} characters minimum" if @minimum_password_length),
                        input_html: { autocomplete: "new-password" },
                        label: 'Nouveau mot de passe',
                        placeholder: 'Laissez vide si vous ne souhaiter pas changer' %>
          </div>
          <div class="col-6">
            <%= f.input :password_confirmation,
                        input_html: { autocomplete: "new-password" },
                        label: 'Confirmer votre nouveau mot de passe',
                        placeholder: 'Laissez vide si vous ne souhaiter pas changer' %>
          </div>
          <div class="col-12">
            <h5 class="my-3">Valider vos changement !</h5>
          </div>
          <div class="col-12">
            <%= f.input :current_password,
                        hint: "Votre mot de passe est obligatoire pour enregistrer vos changements.",
                        required: true,
                        input_html: { autocomplete: "current-password" },
                        label: 'Mot de passe' %>
          </div>
        </div>
      </div>

      <div class="form-actions d-flex-center mt-5 mb-3">
        <%= f.button :submit, "Valider", class: 'btn petch-btn' %>
      </div>
    <% end %>
  </div>
</div>