config/routes.rb
Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  root to: 'pages#home'
  devise_for :users, controllers: { invitations: 'admin/invitations' }

  post '/newsletter', to: 'pages#home'
  get '/profile', to: 'dashboards#user_dashboard'

  get 'card_init', to: 'cards#init'
  get 'animal_select', to: 'articles#animal_select'

  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy], path: 'conseils' do
    member do
      post 'submit'
      post 'top'
    end
  end

  resources :cards, only: [:index, :show, :new, :create, :edit, :update], path: 'fiches' do
    member do
      post 'submit'
    end
  end

  resources :brands, only: [:index, :show], path: 'marques'

  namespace :admin do

    get '/profile', to: 'dashboards#admin_dashboard'

    # get '/invite', to: 'invitations#new'
    # post '/invite', to: 'invitations#create'

    resources :articles, only: [:destroy] do
      post '/publish', to: 'articles#publish'
      post '/unpublish', to: 'articles#unpublish'
    end

    resources :cards, only: [:destroy] do
      post '/publish', to: 'cards#publish'
      post '/unpublish', to: 'cards#unpublish'
    end

    resources :brands, only: [:new, :create, :edit, :update, :destroy] do
      resources :products, only: [:create]
    end

    resources :products, only: [:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController

  def admin_dashboard
    authorize :dashboard, :admin?

    @articles = Article.where(id: articles_select)
    @pagy_articles, @articles = pagy(
      helpers.articles_filter(@articles, params).order(created_at: :desc),
      items: 10,
      page_param: :page_articles,
      params: { active_tab: 'articles' },
      # link_extra: 'data-remote="true"'
    )

    @cards = Card.all
    @pagy_cards, @cards = pagy(
      helpers.cards_filter(@cards, params).order(created_at: :desc),
      items: 10,
      page_param: :page_cards,
      params: { active_tab: 'cards' },
      # link_extra: 'data-remote="true"'
    )

    @brands = Brand.all
    @pagy_brands, @brands = pagy(
      helpers.brands_filter(@brands, params).order(created_at: :desc),
      items: 10,
      page_param: :page_brands,
      params: { active_tab: 'brands' },
      # link_extra: 'data-remote="true"'
    )

    if !params[:active_tab]
      params[:active_tab] = 'articles' if params[:articles_data]
      params[:active_tab] = 'cards' if params[:cards_filter]
      params[:active_tab] = 'brands' if params[:brands_filter]
    end
  end

  private

  def articles_select
    articles = Article.all.select do |a|
      a.user == current_user || a.status == 'submitted' || a.status == 'published' || a.status == 'hidden' || a.top
    end

    return articles.map(&:id)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def user_dashboard
    authorize :dashboard, :profile?

    @articles = current_user.articles
    @pagy, @articles = pagy(
      helpers.dashboard_search(@articles, params).order(created_at: :desc),
      items: 10,
      link_extra: 'data-remote="true"'
    )

    if params[:filter_data]
      respond_to do |format|
        format.html { redirect_to profile_path }
        format.js
      end
    end
  end

  private

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def dashboard_search(articles, params)

    if params[:filter_data]
      articles = articles.search_articles(params[:filter_data][:query]) if !params[:filter_data][:query].blank?
      articles = articles.where(theme: params[:filter_data][:theme]) if !params[:filter_data][:theme].blank?
      articles = articles.where(animal: Animal.find_by(name: params[:filter_data][:animal])) if !params[:filter_data][:animal].blank?
      articles = articles.where(status: params[:filter_data][:status]) if !params[:filter_data][:status].blank?
    end

    return articles
  end

  def articles_filter(articles, params)

    if params[:articles_filter]
      author = User.find_by_email(params[:articles_filter][:user])
      articles = articles.search_articles(params[:articles_filter][:query]) if !params[:articles_filter][:query].blank?
      articles = articles.where(theme: params[:articles_filter][:theme]) if !params[:articles_filter][:theme].blank?
      articles = articles.where(animal: Animal.find_by(name: params[:articles_filter][:animal])) if !params[:articles_filter][:animal].blank?
      articles = articles.where(status: params[:articles_filter][:status]) if !params[:articles_filter][:status].blank?
      articles = articles.where(user: author) if !params[:articles_filter][:user].blank?
      articles = articles.where(top: true) if params[:articles_filter][:top] == 'Oui'
      articles = articles.where(top: false) if params[:articles_filter][:top] == 'Non'
    end

    return articles
  end

  def cards_filter(cards, params)

    if params[:cards_filter]
      cards = cards.cards_search(params[:cards_filter][:query]) if !params[:cards_filter][:query].blank?
      cards = cards.where(animal: Animal.find_by(name: params[:cards_filter][:animal])) if !params[:cards_filter][:animal].blank?
      cards = cards.where(status: params[:cards_filter][:status]) if !params[:cards_filter][:status].blank?
    end

    return cards
  end

  def brands_filter(brands, params)

    if params[:brands_filter]
      brands = brands.brands_search(params[:brands_filter][:query]) if !params[:brands_filter][:query].blank?
      brands = Brand.where(id: brands.select { |b| b.animals.pluck(:name).include?(params[:brands_filter][:animal]) }.map(&:id)) if !params[:brands_filter][:animal].blank?
    end

    return brands
  end

  # DEVISE

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/dashboards/_articles_tab.html.erb
<div class="dashboard-articles">
  <% articles.each do |article| %>
    <div id="article-<%= article.id %>">
      <%= render 'dashboard_article_card', article: article %>
    </div>
  <% end %>
  <hr>
  <div class="pagination">
    <%= render 'shared/pagination', pagy: @pagy %>
  </div>
</div>

app/views/dashboards/_dashboard_article_card.html.erb
<div class="dashboard-article-card">
  <%= image_tag url_for(article.thumbnail) %>

  <div class="artcile-infos">
    <span>ID: <%= article.id %></span>
    <span>Titre: <%= article.title %></span>
    <span>Sous-titre: <%= article.subtitle %></span>
    <span>Thème: <%= article.theme %></span>
    <span>Auteur: <%= article.author_name %></span>
  </div>

  <div class="article-status-info">
    <span class="status">Status</span>
    <% if article.status == 'draft' %>
      <div class="article-status draft"><%= article.status %></div>
    <% end %>

    <% if article.status == 'published' %>
      <div class="article-status published"><%= article.status %></div>
    <% end %>

    <% if article.status == 'submitted' %>
      <span class="article-status submitted"><%= article.status %></span>
    <% end %>

    <% if article.status == 'hidden' %>
      <span class="article-status hidden"><%= article.status %></span>
    <% end %>
  </div>

  <div class="article-controls">
    <% if current_user.is_writer? %>
      <% if article.status == 'draft' %>
        <span>
          <i class="fas fa-paper-plane"></i>
          <%= link_to 'Submit', submit_article_path(article), method: :post, remote: true %>
        </span>
        <span>
          <i class="fas fa-trash-alt"></i>
          <%= link_to 'Supprimer', article_path(article), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
        </span>
      <% end %>

      <% if article.status == 'hidden' %>
        <span>
          <i class="fas fa-paper-plane"></i>
          <%= link_to 'Submit', submit_article_path(article), method: :post, remote: true %>
        </span>
      <% end %>

      <% if article.status == 'draft' || article.status == 'hidden' %>
        <span>
          <i class="fas fa-pen"></i>
          <%= link_to 'Editer', edit_article_path(article) %>
        </span>
      <% end %>

      <span>
        <i class="far fa-eye"></i>
        <%= link_to 'Voir', article_path(article) %>
      </span>
    <% end %>

    <% if current_user.is_admin? %>
      <span>
        <%= link_to top_article_path(article), method: :post, remote: true do %>
          <% if article.top %>
            <i class="fas fa-star top-star-on"></i>
          <% else %>
            <i class="fas fa-star top-star-off"></i>
          <% end %>
        <% end %>
      </span>
      <% if article.status == 'draft' || article.status == 'submitted' || article.status == 'hidden' %>
        <span>
          <i class="fas fa-paper-plane"></i>
          <%= link_to 'Publier', admin_article_publish_path(article), method: :post, remote: true %>
        </span>
      <% else %>
        <span>
          <i class="far fa-eye-slash"></i>
          <%= link_to 'Masquer', admin_article_unpublish_path(article), method: :post, remote: true %>
        </span>
      <% end %>
      <span>
        <i class="fas fa-pen"></i>
        <%= link_to 'Editer', edit_article_path(article) %>
      </span>
      <span>
        <i class="far fa-eye"></i>
        <%= link_to 'Voir', article_path(article) %>
      </span>
      <span>
        <i class="fas fa-trash-alt"></i>
        <%= link_to 'Supprimer', article_path(article), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
      </span>
    <% end %>
  </div>
</div>

app/views/dashboards/_dashboard_card_card.html.erb
<div class="dashboard-article-card">
  <%= image_tag url_for(card.thumbnail) %>

  <div class="artcile-infos">
    <span>id: <%= card.id %></span>
    <span>specie: <%= card.specie.name %></span>
    <span>Author: <%= card.author_name %></span>
  </div>

  <div class="article-status-info">
    <span class="status">Status</span>
    <% if card.status == 'draft' %>
      <div class="article-status draft"><%= card.status %></div>
    <% end %>

    <% if card.status == 'published' %>
      <div class="article-status published"><%= card.status %></div>
    <% end %>

    <% if card.status == 'submitted' %>
      <span class="article-status submitted"><%= card.status %></span>
    <% end %>
  </div>

  <div class="article-controls">
    <% if current_user.is_writer? %>
      <span>
        <i class="fas fa-pen"></i>
        <%= link_to 'Editer', edit_card_path(card) %>
      </span>
      <span>
        <i class="far fa-eye"></i>
        <%= link_to 'Voir', card_path(card) %>
      </span>
    <% end %>

    <% if current_user.is_admin? %>
      <% if card.status == 'draft' || card.status == 'submitted' %>
        <span>
          <i class="fas fa-paper-plane"></i>
          <%= link_to 'Publier', admin_card_publish_path(card), method: :post %>
        </span>
      <% end %>
      <span>
        <i class="fas fa-pen"></i>
        <%= link_to 'Editer', edit_card_path(card) %>
      </span>
      <span>
        <i class="far fa-eye"></i>
        <%= link_to 'Voir', card_path(card) %>
      </span>
    <% end %>
  </div>
</div>

app/views/dashboards/_nav_articles_tab.html.erb
<div class="tab-pane fade show active" id="nav-articles" role="tabpanel" aria-labelledby="nav-articles-tab">
  <%= simple_form_for :filter_data, url: profile_path, method: :get, remote: true do |f| %>
    <div class="form-row dashboard-filter">
      <div class="col-4">
        <%= f.input :query, label: false, placeholder: 'Rechercher...' %>
      </div>
      <div class="col">
        <%= f.input :theme, collection: Article::THEMES, label: false, prompt: 'Thème' %>
      </div>
      <div class="col">
        <%= f.input :animal, collection: Animal.pluck(:name), label: false, prompt: 'Animal' %>
      </div>
      <div class="col">
        <%= f.input :status, collection: Article::STATUS, label: false, prompt: 'Statut' %>
      </div>
      <div class="col-1">
        <%= f.submit 'Filtrer', class: 'btn btn-primary' %>
      </div>
    </div>
  <% end %>
  <div id="articles-tab-wrapper">
    <%= render 'articles_tab', articles: @articles %>
  </div>
</div>

app/views/dashboards/_nav_profile_tab.html.erb
<div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
  <%= render 'shared/registration_edit_form' %>
</div>

app/views/dashboards/_nav_write_tab.html.erb
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
<div class="tab-pane fade" id="nav-write" role="tabpanel" aria-labelledby="nav-write-tab">
  <div class="container">
    <div class="new-row">
      <button class="write-nav"><%= link_to "Nouveau conseil", new_article_path %></button>
    </div>
  </div>
</div>

app/views/dashboards/user_dashboard.html.erb
<div class="dashboard-wrapper">
  <div class="dashboard-header">
    <div class="dashboard-header-content">
      <h1>Mon Profil Editeur</h1>
    </div>
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Mon Profil</a>
        <a class="nav-item nav-link active" id="nav-articles-tab" data-toggle="tab" href="#nav-articles" role="tab" aria-controls="nav-articles" aria-selected="true">Mes Conseils</a>
        <a class="nav-item nav-link" id="nav-write-tab" data-toggle="tab" href="#nav-write" role="tab" aria-controls="nav-write" aria-selected="false">Ecrire du contenu</a>
      </div>
    </nav>
  </div>

  <div class="container py-5">
    <div class="tab-content" id="nav-tabContent">
      <%= render "nav_articles_tab" %>
      <%= render "nav_profile_tab" %>
      <%= render "nav_write_tab" %>
    </div>
  </div>
</div>

app/views/dashboards/user_dashboard.js.erb
document.querySelector('#articles-tab-wrapper').innerHTML = '<%= j render "articles_tab", articles: @articles %>'