config/routes.rb
Rails.application.routes.draw do
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server_error'

  root to: 'pages#home'
  devise_for :users, controllers: { invitations: 'admin/invitations' }

  post '/newsletter', to: 'pages#home'
  get '/profile', to: 'dashboards#user_dashboard'

  get 'card_init', to: 'cards#init'
  get 'animal_select', to: 'articles#animal_select'

  resources :articles, only: [:index, :show, :new, :create, :edit, :update, :destroy], path: 'conseils' do
    member do
      post 'submit'
      post 'top'
    end
  end

  resources :cards, only: [:index, :show, :new, :create, :edit, :update], path: 'fiches' do
    member do
      post 'submit'
    end
  end

  resources :brands, only: [:index, :show], path: 'marques'

  namespace :admin do

    get '/profile', to: 'dashboards#admin_dashboard'

    # get '/invite', to: 'invitations#new'
    # post '/invite', to: 'invitations#create'

    resources :articles, only: [:destroy] do
      post '/publish', to: 'articles#publish'
      post '/unpublish', to: 'articles#unpublish'
    end

    resources :cards, only: [:destroy] do
      post '/publish', to: 'cards#publish'
      post '/unpublish', to: 'cards#unpublish'
    end

    resources :brands, only: [:new, :create, :edit, :update, :destroy] do
      resources :products, only: [:create]
    end

    resources :products, only: [:destroy]
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin/dashboards_controller.rb
class Admin::DashboardsController < ApplicationController

  def admin_dashboard
    authorize :dashboard, :admin?

    @articles = Article.where(id: articles_select)
    @pagy_articles, @articles = pagy(
      helpers.articles_filter(@articles, params).order(created_at: :desc),
      items: 10,
      page_param: :page_articles,
      params: { active_tab: 'articles' },
      # link_extra: 'data-remote="true"'
    )

    @cards = Card.all
    @pagy_cards, @cards = pagy(
      helpers.cards_filter(@cards, params).order(created_at: :desc),
      items: 10,
      page_param: :page_cards,
      params: { active_tab: 'cards' },
      # link_extra: 'data-remote="true"'
    )

    @brands = Brand.all
    @pagy_brands, @brands = pagy(
      helpers.brands_filter(@brands, params).order(created_at: :desc),
      items: 10,
      page_param: :page_brands,
      params: { active_tab: 'brands' },
      # link_extra: 'data-remote="true"'
    )

    if !params[:active_tab]
      params[:active_tab] = 'articles' if params[:articles_data]
      params[:active_tab] = 'cards' if params[:cards_filter]
      params[:active_tab] = 'brands' if params[:brands_filter]
    end
  end

  private

  def articles_select
    articles = Article.all.select do |a|
      a.user == current_user || a.status == 'submitted' || a.status == 'published' || a.status == 'hidden' || a.top
    end

    return articles.map(&:id)
  end

end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def user_dashboard
    authorize :dashboard, :profile?

    @articles = current_user.articles
    @pagy, @articles = pagy(
      helpers.dashboard_search(@articles, params).order(created_at: :desc),
      items: 10,
      link_extra: 'data-remote="true"'
    )

    if params[:filter_data]
      respond_to do |format|
        format.html { redirect_to profile_path }
        format.js
      end
    end
  end

  private

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
  def dashboard_search(articles, params)

    if params[:filter_data]
      articles = articles.search_articles(params[:filter_data][:query]) if !params[:filter_data][:query].blank?
      articles = articles.where(theme: params[:filter_data][:theme]) if !params[:filter_data][:theme].blank?
      articles = articles.where(animal: Animal.find_by(name: params[:filter_data][:animal])) if !params[:filter_data][:animal].blank?
      articles = articles.where(status: params[:filter_data][:status]) if !params[:filter_data][:status].blank?
    end

    return articles
  end

  def articles_filter(articles, params)

    if params[:articles_filter]
      author = User.find_by_email(params[:articles_filter][:user])
      articles = articles.search_articles(params[:articles_filter][:query]) if !params[:articles_filter][:query].blank?
      articles = articles.where(theme: params[:articles_filter][:theme]) if !params[:articles_filter][:theme].blank?
      articles = articles.where(animal: Animal.find_by(name: params[:articles_filter][:animal])) if !params[:articles_filter][:animal].blank?
      articles = articles.where(status: params[:articles_filter][:status]) if !params[:articles_filter][:status].blank?
      articles = articles.where(user: author) if !params[:articles_filter][:user].blank?
      articles = articles.where(top: true) if params[:articles_filter][:top] == 'Oui'
      articles = articles.where(top: false) if params[:articles_filter][:top] == 'Non'
    end

    return articles
  end

  def cards_filter(cards, params)

    if params[:cards_filter]
      cards = cards.cards_search(params[:cards_filter][:query]) if !params[:cards_filter][:query].blank?
      cards = cards.where(animal: Animal.find_by(name: params[:cards_filter][:animal])) if !params[:cards_filter][:animal].blank?
      cards = cards.where(status: params[:cards_filter][:status]) if !params[:cards_filter][:status].blank?
    end

    return cards
  end

  def brands_filter(brands, params)

    if params[:brands_filter]
      brands = brands.brands_search(params[:brands_filter][:query]) if !params[:brands_filter][:query].blank?
      brands = Brand.where(id: brands.select { |b| b.animals.pluck(:name).include?(params[:brands_filter][:animal]) }.map(&:id)) if !params[:brands_filter][:animal].blank?
    end

    return brands
  end

  # DEVISE

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/admin/dashboards/_articles_tab.html.erb
<div class="dashboard-articles">
  <% articles.each do |article| %>
    <div id="article-<%= article.id %>">
      <%= render 'dashboards/dashboard_article_card', article: article %>
    </div>
  <% end %>
  <%= render 'shared/pagination', pagy: @pagy_articles %>
</div>

app/views/admin/dashboards/_brands_tab.html.erb
<div class="dashboard-brands">
  <% brands.each do |brand| %>
    <div id="brand-<%= brand.id %>">
      <%= render 'admin/dashboards/dashboard_brand_card', brand: brand %>
    </div>
  <% end %>
  <%= render 'shared/pagination', pagy: @pagy_brands %>
</div>

app/views/admin/dashboards/_cards_list.html.erb
<% cards.each do |card| %>
  <div id="card-<%= card.id %>">
    <%= render 'admin/dashboards/dashboard_card_card', card: card %>
  </div>
<% end %>

app/views/admin/dashboards/_cards_tab.html.erb
<div class="dashboard-cards">
  <% cards.each do |card| %>
    <div id="card-<%= card.id %>">
      <%= render 'admin/dashboards/dashboard_card_card', card: card %>
    </div>
  <% end %>
  <%= render 'shared/pagination', pagy: @pagy_cards %>
</div>

app/views/admin/dashboards/_dashboard_brand_card.html.erb
<div class="dashboard-article-card dashboard-brand-card">
  <%= image_tag url_for(brand.logo) %>

  <div class="artcile-infos">
    <span>ID: <%= brand.id %></span>
    <span>Nom: <%= brand.name %></span>
  </div>

  <div class="article-status-info">

  </div>

  <div class="article-controls">
    <%= render 'shared/new_product_modal', brand: brand %>
    <span>
      <i class="fas fa-pen"></i>
      <%= link_to 'Editer', edit_admin_brand_path(brand) %>
    </span>
    <span>
      <i class="far fa-eye"></i>
      <%= link_to 'Voir', brand_path(brand) %>
    </span>
    <span>
      <i class="fas fa-trash-alt"></i>
      <%= link_to 'Supprimer', admin_brand_path(brand), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
    </span>
  </div>
</div>

app/views/admin/dashboards/_dashboard_card_card.html.erb
<div class="dashboard-article-card">
  <%= image_tag url_for(card.thumbnail) %>

  <div class="artcile-infos">
    <span>ID: <%= card.id %></span>
    <span>Espece: <%= card.specie.name %></span>
    <span>Auteur: <%= card.author_name %></span>
  </div>

  <div class="article-status-info">
    <span class="status">Status</span>
    <% if card.status == 'draft' %>
      <div class="article-status draft"><%= card.status %></div>
    <% end %>

    <% if card.status == 'published' %>
      <div class="article-status published"><%= card.status %></div>
    <% end %>

    <% if card.status == 'submitted' %>
      <span class="article-status submitted"><%= card.status %></span>
    <% end %>
  </div>

  <div class="article-controls">
    <% if current_user.is_admin? %>
      <% if card.status == 'draft' %>
        <span>
          <i class="fas fa-paper-plane"></i>
          <%= link_to 'Publier', admin_card_publish_path(card), method: :post, remote: true %>
        </span>
      <% else %>
        <span>
          <i class="far fa-eye-slash"></i>
          <%= link_to 'Masquer', admin_card_unpublish_path(card), method: :post, remote: true %>
        </span>
      <% end %>
      <span>
        <i class="fas fa-pen"></i>
        <%= link_to 'Editer', edit_card_path(card) %>
      </span>
      <span>
        <i class="far fa-eye"></i>
        <%= link_to 'Voir', card_path(card) %>
      </span>
      <span>
        <i class="fas fa-trash-alt"></i>
        <%= link_to 'Supprimer', admin_card_path(card), method: :delete, remote: true, data: { confirm: 'Are you sure?' } %>
      </span>
    <% end %>
  </div>
</div>

app/views/admin/dashboards/admin_dashboard.html.erb
<div class="dashboard-wrapper">
  <div class="dashboard-header">
    <div class="dashboard-header-content">
      <h1>Mon Profil Admin</h1>
    </div>
    <nav>
      <div class="nav nav-tabs" id="nav-tab" role="tablist">
        <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false">Mon Profil</a>
        <a class="nav-item nav-link <%= 'active' if params[:active_tab] == 'articles' || params[:active_tab] == nil %>" id="nav-articles-tab" data-toggle="tab" href="#nav-articles" role="tab" aria-controls="nav-articles" aria-selected="true">Conseils</a>
        <a class="nav-item nav-link <%= 'active' if params[:active_tab] == 'cards' %>" id="nav-fiches-tab" data-toggle="tab" href="#nav-fiches" role="tab" aria-controls="nav-fiches" aria-selected="false">Fiches</a>
        <a class="nav-item nav-link <%= 'active' if params[:active_tab] == 'brands' %>" id="nav-marques-tab" data-toggle="tab" href="#nav-marques" role="tab" aria-controls="nav-marques" aria-selected="false">Marques</a>
        <a class="nav-item nav-link" id="nav-content-write" data-toggle="tab" href="#nav-write" role="tab" aria-controls="nav-fiches" aria-selected="false">Écrire du contenu</a>
      </div>
    </nav>
  </div>

  <div class="container py-5">

    <div class="tab-content" id="nav-tabContent">

      <div class="tab-pane fade <%= 'show active' if params[:active_tab] == 'articles' || params[:active_tab] == nil %>" id="nav-articles" role="tabpanel" aria-labelledby="nav-articles-tab">
        <%= simple_form_for :articles_filter, url: admin_profile_path, method: :get do |f| %>
          <div class="form-row align-items-center dashboard-filter">
            <div class="col-3">
              <%= f.input :query, label: false, placeholder: 'Rechercher...' %>
            </div>
            <div class="col-2">
              <%= f.input :theme, collection: Article::THEMES, label: false, prompt: 'Thème' %>
            </div>
            <div class="col-1">
              <%= f.input :animal, collection: Animal.pluck(:name), label: false, prompt: 'Animal' %>
            </div>
            <div class="col-2">
              <%= f.input :status, collection: Article::STATUS, label: false, prompt: 'Statut' %>
            </div>
            <div class="col-2">
              <%= f.input :user, collection: User.pluck(:email), label: false, prompt: 'Utilisateur' %>
            </div>
            <div class="col-1">
              <%= f.input :top, collection: ['Oui', 'Non'], label: false, prompt: 'A la une' %>
            </div>
            <div class="col-1">
              <%= f.submit 'Filtrer', class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
        <div id="articles-tab-wrapper">
          <%= render 'articles_tab', articles: @articles %>
        </div>
      </div>


      <div class="tab-pane fade <%= 'show active' if params[:active_tab] == 'cards' %>" id="nav-fiches" role="tabpanel" aria-labelledby="nav-fiches-tab">
        <%= simple_form_for :cards_filter, url: admin_profile_path, method: :get do |f| %>
          <div class="form-row align-items-center dashboard-filter">
            <div class="col-4">
              <%= f.input :query, label: false, placeholder: 'Rechercher...' %>
            </div>
            <div class="col">
              <%= f.input :animal, collection: Animal.pluck(:name), label: false, prompt: 'Animal' %>
            </div>
            <div class="col">
              <%= f.input :status, collection: Card::STATUS, label: false, prompt: 'Statut' %>
            </div>
            <div class="col-2">
              <%= f.submit 'Filtrer', class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
        <%= render 'cards_tab', cards: @cards %>
      </div>

      <div class="tab-pane fade <%= 'show active' if params[:active_tab] == 'brands' %>" id="nav-marques" role="tabpanel" aria-labelledby="nav-marques-tab">
        <%= simple_form_for :brands_filter, url: admin_profile_path, method: :get do |f| %>
          <div class="form-row align-items-center dashboard-filter">
            <div class="col-5">
              <%= f.input :query, label: false, placeholder: 'Rechercher...' %>
            </div>
            <div class="col-5">
              <%= f.input :animal, collection: Animal.pluck(:name), label: false, prompt: 'Animal' %>
            </div>
            <div class="col-2">
              <%= f.submit 'Filtrer', class: 'btn btn-primary' %>
            </div>
          </div>
        <% end %>
        <%= render 'brands_tab', brands: @brands %>
      </div>

      <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
        <%= render 'shared/registration_edit_form' %>
      </div>

      <div class="tab-pane fade" id="nav-write" role="tabpanel" aria-labelledby="nav-content-write">
        <div class="container">
          <div class="new-row">
            <button class="write-nav"><%= link_to "Invitation", new_user_invitation_path %></button>
            <button id="new-card-button" class="write-nav">Nouvelle fiche</button>
            <button class="write-nav"><%= link_to "Nouveau conseil", new_article_path %></button>
            <button class="write-nav"><%= link_to "Nouvelle Marque", new_admin_brand_path %></button>
          </div>

          <div class="new-row animals-row hidden">
            <button class="write-nav"><%= link_to "Chien", new_card_path(animal: 'chien') %></button>
            <button class="write-nav"><%= link_to "Chat", new_card_path(animal: 'chat') %></button>
            <button class="write-nav"><%= link_to "Rongeur", new_card_path(animal: 'rongeur') %></button>
          </div>
        </div>
      </div>

    </div>

  </div>

  <script>
    const animals = document.querySelector('.animals-row')
    document.getElementById('new-card-button').addEventListener('click', ((event) => {
      animals.classList.remove('hidden')
    }))
  </script>
</div>

app/views/admin/dashboards/admin_dashboard.js.erb
document.querySelector('#articles-tab-wrapper').innerHTML = '<%= j render "articles_tab", articles: @articles %>'

document.querySelector('#cards-list').innerHTML = '<%= j render "cards_list", cards: @cards %>'